-- Sheet: 02_rbac
-- Purpose: roles, grants, future grants
-- Role needed: SECURITYADMIN
-- Date: 22-Mar-2026

USE ROLE SECURITYADMIN;

-- Access roles (own the actual privileges)
CREATE ROLE AR_RAW_RW       COMMENT = 'Read+write on RAW';
CREATE ROLE AR_STAGING_RW   COMMENT = 'Read+write on STAGING';
CREATE ROLE AR_STAGING_RO   COMMENT = 'Read-only on STAGING';
CREATE ROLE AR_MARTS_RW     COMMENT = 'Read+write on MARTS';
CREATE ROLE AR_MARTS_RO     COMMENT = 'Read-only on MARTS';

-- Functional roles (map to job titles)
CREATE ROLE FR_DATA_ENGINEER  COMMENT = 'Full pipeline access';
CREATE ROLE FR_DATA_ANALYST   COMMENT = 'Query cleaned data';
CREATE ROLE FR_DBT_SERVICE    COMMENT = 'Service account for dbt';

-- Roll up to SYSADMIN
GRANT ROLE AR_RAW_RW       TO ROLE SYSADMIN;
GRANT ROLE AR_STAGING_RW   TO ROLE SYSADMIN;
GRANT ROLE AR_STAGING_RO   TO ROLE SYSADMIN;
GRANT ROLE AR_MARTS_RW     TO ROLE SYSADMIN;
GRANT ROLE AR_MARTS_RO     TO ROLE SYSADMIN;
GRANT ROLE FR_DATA_ENGINEER TO ROLE SYSADMIN;
GRANT ROLE FR_DATA_ANALYST  TO ROLE SYSADMIN;
GRANT ROLE FR_DBT_SERVICE   TO ROLE SYSADMIN;

SHOW ROLES;

-- Grants: object privileges to access roles
USE ROLE SYSADMIN;

-- RAW schema
GRANT USAGE ON DATABASE ECOMM_DB          TO ROLE AR_RAW_RW;
GRANT USAGE ON SCHEMA ECOMM_DB.RAW        TO ROLE AR_RAW_RW;
GRANT ALL ON ALL TABLES
  IN SCHEMA ECOMM_DB.RAW                  TO ROLE AR_RAW_RW;
GRANT ALL ON FUTURE TABLES
  IN SCHEMA ECOMM_DB.RAW                  TO ROLE AR_RAW_RW;
GRANT CREATE TABLE, CREATE STAGE
  ON SCHEMA ECOMM_DB.RAW                  TO ROLE AR_RAW_RW;

-- STAGING schema
GRANT USAGE ON DATABASE ECOMM_DB          TO ROLE AR_STAGING_RW;
GRANT USAGE ON SCHEMA ECOMM_DB.STAGING    TO ROLE AR_STAGING_RW;
GRANT ALL ON ALL TABLES
  IN SCHEMA ECOMM_DB.STAGING              TO ROLE AR_STAGING_RW;
GRANT ALL ON FUTURE TABLES
  IN SCHEMA ECOMM_DB.STAGING              TO ROLE AR_STAGING_RW;

GRANT USAGE ON DATABASE ECOMM_DB          TO ROLE AR_STAGING_RO;
GRANT USAGE ON SCHEMA ECOMM_DB.STAGING    TO ROLE AR_STAGING_RO;
GRANT SELECT ON ALL TABLES
  IN SCHEMA ECOMM_DB.STAGING              TO ROLE AR_STAGING_RO;
GRANT SELECT ON FUTURE TABLES
  IN SCHEMA ECOMM_DB.STAGING              TO ROLE AR_STAGING_RO;

-- MARTS schema
GRANT USAGE ON DATABASE ECOMM_DB          TO ROLE AR_MARTS_RW;
GRANT USAGE ON SCHEMA ECOMM_DB.MARTS      TO ROLE AR_MARTS_RW;
GRANT ALL ON ALL TABLES
  IN SCHEMA ECOMM_DB.MARTS                TO ROLE AR_MARTS_RW;
GRANT ALL ON FUTURE TABLES
  IN SCHEMA ECOMM_DB.MARTS                TO ROLE AR_MARTS_RW;

GRANT USAGE ON DATABASE ECOMM_DB          TO ROLE AR_MARTS_RO;
GRANT USAGE ON SCHEMA ECOMM_DB.MARTS      TO ROLE AR_MARTS_RO;
GRANT SELECT ON ALL TABLES
  IN SCHEMA ECOMM_DB.MARTS                TO ROLE AR_MARTS_RO;
GRANT SELECT ON FUTURE TABLES
  IN SCHEMA ECOMM_DB.MARTS                TO ROLE AR_MARTS_RO;

-- Bundle access roles into functional roles
GRANT ROLE AR_RAW_RW      TO ROLE FR_DATA_ENGINEER;
GRANT ROLE AR_STAGING_RW  TO ROLE FR_DATA_ENGINEER;
GRANT ROLE AR_MARTS_RW    TO ROLE FR_DATA_ENGINEER;

GRANT ROLE AR_STAGING_RO  TO ROLE FR_DATA_ANALYST;
GRANT ROLE AR_MARTS_RO    TO ROLE FR_DATA_ANALYST;

GRANT ROLE AR_RAW_RW      TO ROLE FR_DBT_SERVICE;
GRANT ROLE AR_STAGING_RW  TO ROLE FR_DBT_SERVICE;
GRANT ROLE AR_MARTS_RW    TO ROLE FR_DBT_SERVICE;

-- Warehouse access
GRANT USAGE ON WAREHOUSE LOAD_WH       TO ROLE FR_DATA_ENGINEER;
GRANT USAGE ON WAREHOUSE TRANSFORM_WH  TO ROLE FR_DATA_ENGINEER;
GRANT USAGE ON WAREHOUSE TRANSFORM_WH  TO ROLE FR_DBT_SERVICE;
GRANT USAGE ON WAREHOUSE ANALYTICS_WH  TO ROLE FR_DATA_ANALYST;

-- Assign to your user
USE ROLE SECURITYADMIN;
GRANT ROLE FR_DATA_ENGINEER TO USER dev_user;
SELECT CURRENT_USER();
GRANT ROLE FR_DATA_ENGINEER TO USER BISWAS;

SHOW GRANTS TO USER BISWAS;


USE ROLE SYSADMIN;

GRANT CREATE FILE FORMAT ON SCHEMA ECOMM_DB.RAW TO ROLE AR_RAW_RW;
GRANT CREATE STAGE       ON SCHEMA ECOMM_DB.RAW TO ROLE AR_RAW_RW;


USE ROLE SYSADMIN;

GRANT CREATE TABLE ON SCHEMA ECOMM_DB.STAGING TO ROLE AR_STAGING_RW;
GRANT CREATE VIEW  ON SCHEMA ECOMM_DB.STAGING TO ROLE AR_STAGING_RW;
GRANT CREATE TABLE ON SCHEMA ECOMM_DB.MARTS   TO ROLE AR_MARTS_RW;
GRANT CREATE VIEW  ON SCHEMA ECOMM_DB.MARTS   TO ROLE AR_MARTS_RW;

USE ROLE SYSADMIN;

GRANT CREATE STREAM ON SCHEMA ECOMM_DB.RAW     TO ROLE AR_RAW_RW;
GRANT CREATE STREAM ON SCHEMA ECOMM_DB.STAGING TO ROLE AR_STAGING_RW;
GRANT CREATE TASK   ON SCHEMA ECOMM_DB.STAGING TO ROLE AR_STAGING_RW;