--Sheet: 01_database
-- Purpose: create ECOMM_DB and medallion schemas
-- Role needed: SYSADMIN
-- Date: 22-Mar-2026


-- Sheet: 01_database
-- Purpose: create ECOMM_DB and medallion schemas
-- Role needed: SYSADMIN
-- Date: 22-Mar-2026

USE ROLE SYSADMIN;
USE WAREHOUSE TRANSFORM_WH;

CREATE DATABASE ECOMM_DB
  COMMENT = 'E-commerce analytics platform';

CREATE SCHEMA ECOMM_DB.RAW
  COMMENT = 'Bronze — raw ingested data, no transforms';

CREATE SCHEMA ECOMM_DB.STAGING
  COMMENT = 'Silver — cleaned and typed';

CREATE SCHEMA ECOMM_DB.MARTS
  COMMENT = 'Gold — aggregated, BI ready';

CREATE SCHEMA ECOMM_DB.AUDIT
  COMMENT = 'Pipeline logs and data quality';

SHOW SCHEMAS IN DATABASE ECOMM_DB;

USE ROLE SYSADMIN;
ALTER WAREHOUSE TRANSFORM_WH
  SET WAREHOUSE_SIZE = XSMALL;

USE ROLE ACCOUNTADMIN;
DROP RESOURCE MONITOR project_guard;

CREATE RESOURCE MONITOR project_guard
  WITH CREDIT_QUOTA   = 400
       FREQUENCY      = MONTHLY
       START_TIMESTAMP = IMMEDIATELY
       TRIGGERS
         ON 50 PERCENT DO NOTIFY
         ON 75 PERCENT DO NOTIFY
         ON 90 PERCENT DO SUSPEND
         ON 100 PERCENT DO SUSPEND_IMMEDIATE;

ALTER WAREHOUSE LOAD_WH
  SET RESOURCE_MONITOR = project_guard;
ALTER WAREHOUSE TRANSFORM_WH
  SET RESOURCE_MONITOR = project_guard;
ALTER WAREHOUSE ANALYTICS_WH
  SET RESOURCE_MONITOR = project_guard;

SHOW RESOURCE MONITORS;

USE ROLE ACCOUNTADMIN;
ALTER WAREHOUSE LOAD_WH      SUSPEND;
ALTER WAREHOUSE TRANSFORM_WH SUSPEND;
ALTER WAREHOUSE ANALYTICS_WH SUSPEND;

SHOW WAREHOUSES;